### ISSUE TITLE
File Color plugin appears broken in Ver 1.2.1

### ISSUE THREAD

**Issue by ThePainterMan** [ecustic/obsidian-file-color#9]
I have just updated Obsidian (or rather the auto-update did this for me) to version 1.2.1 and the File Color plugin is no longer working. None of my files are showing any colour (all files are just black) and if I go to apply a colour using the active plugin...nothing visibly happens.

**Comment by jockstersi** [comment]
I am also seeing this issue.

**Comment by ecustic** [comment]
The latest stable release of Obsidian is v1.1.16, which means if you are running v1.2.1 you've opted in for the insider builds of Obsidian. I'm not planning on supporting insider builds as they are development builds and are by their nature prone to being buggy and incomplete. Once the build stabilizes and gets an official release, I will check to make sure that the plugin works as intended on the newest stable version.

**Comment by jockstersi** [comment]
Thanks for the info. Really appreciate the work on the plugin, cheers Simon
